# Code of Conduct {#code}

## General

In addition to the general expectations laid out above, I am dedicated to making our lab a safe, inclusive, and welcoming environment for all. Below you can find a specific code of conduct for behavior in the lab, as well as a broader discussion of what constitutes an inclusive environment. For more information on professional conduct see the [UW SoM Policy on Professional Conduct](https://www.gs.washington.edu/office/facultyresources/policies/conduct.pdf).

I encourage you also to visit the departmental site dedicated to [diversity, equity, and inclusion (DEI)](https://www.gs.washington.edu/about/dei/index.htm) as well as the UW HR site for DEI information: https://hr.uw.edu/diversity/

## Building an Inclusive Lab Environment

All members of the lab, along with visitors, are expected to agree to the following code of conduct. More information on UW anti-harassment resources are available through the [GS website](https://www.gs.washington.edu/academics/gradprogram/handbook/general/antiharassment.htm).

### Code of Conduct

The lab is dedicated to providing a harassment-free experience for everyone, regardless of gender, gender identity and expression, age, sexual orientation, disability, socioeconomic status, physical appearance, body size, race, national origin, or religion (or lack thereof). We do not tolerate harassment of lab members in any form.

All lab members will treat one another with respect and be sensitive to how one’s words and actions impact others. We do not tolerate the perpetuation of stereotypes; we do not tolerate other acts of microaggression ([more information](https://www.washington.edu/teaching/topics/inclusive-teaching/addressing-microaggressions-in-the-classroom/) via the UW CTL). We are a team. We stand up for one another. We learn from each other. We hold each other accountable.

### Conflict Resolution

In a field based on inquisitive questioning and generation of robust and reproducible data, conflicts can arise. These can be around daily business of working in the lab or more generally for how experiments are conducted.

UW has resources for general conflict negotiation: https://hr.uw.edu/leadershipcafe/wp-content/uploads/sites/20/2020/01/Conflict-Resolution-Creating-an-Effective-Atmosphere.pdf

*As noted in the above work:*
When people are involved in a conflict, there is typically a lot of negative energy. Anger, frustration, and disappointment are just a few of the emotions often felt. By establishing a positive atmosphere, we can begin to turn that negative energy around, and create a powerful problemsolving force. This creates a strong beginning for the conflict resolution process.

In the spirit of teamwork within the lab, I encourage each of you to talk openly with each other where possible. CC'ing me on emails can help to loop me in so that I can help with conflict resolution. An important thing to keep in mind is that each and every person is here to do great science and the goal is to have a workplace in keeping with the code of conduct above. If conflicts arise that results from issues with lab safety please notify me immediately!

We acknowledge that everyone is capable of making mistakes, but our goal is to support each other to achieve the best work and training possible.

## Scientific Integrity

### Reproducible Research

I expect that all of our research will be, at minimum, reproducible (when possible, we will also test for replicability). There are two main things you can do to improve the reproducibility of your research: 1) extensive note-taking (i.e., as much as you can manage) and 2) programming workflows with version control.

Programming workflows help with reproducibility because they take some of the human element out, and in an ideal scenario, you are left with a script or series of scripts that takes data from raw form to final product. Programming alone is not enough, though, because people can easily forget which script changes they made and when. Therefore, all projects that involve programming of any kind (so basically, all projects) must use some form of version control. I strongly recommend git in combination with GitHub (see below), unless you have a pre-existing workflow.

### Authorship

Authorship will be discussed prior to the beginning of a new project, so that expectations are clearly defined. However, changes to authorship may occur over the course of a project if a new person becomes involved or if someone is not fulfilling their planned role. In general, graduate students and postdocs will be a first author on publications on which they are the primary lead, and I will be a last/corresponding author.

### Old Projects

For projects that are grant funded or required significant lab resources (e.g. large scale proteomics experiments): While you are a member of the lab, project "ownership" expires 1 year after data collection has ended or whenever the original primary lead relinquishes their rights to the study, whichever comes first. At that point, I reserve the right to re-assign the project (or not) as needed to expedite publication. Barring specific discussion between you and I, I also reserve the right to re-assign projects and lab resources when you are on extended leave or leave the lab altogether to ensure that projects and publications can be completed effciently. This policy is intended to avoid situations in which a dataset languishes for a long period of time, while still giving publication priority to the original primary lead.
