# General Policies {#general}

## PI Availability
I will be working on campus and available for meetings most days of the week. If my door is open, feel free to come say "hi". Barring an emergency, if my door is closed, send me a message or try me later rather than knock. I’m also happy to set ad-hoc meetings to discuss anything beyond weekly lab and individual meetings.

When working remotely, I’ll be similarly available over Slack and for ad-hoc meetings during regular office hours.


## Meetings

### Lab Meetings & Journal Club
Weekly lab meetings will be focused on project presentations and going over new data/methods. Lab meetings will last 1.5 hours. If at the end of 1.5 hours, we need more time to discuss something, we will schedule another meeting. Lab meeting plans and notes will be maintained in the #lab_-_meetings channel on Slack. **All full-time lab members** are expected to attend the weekly lab meeting. All part-time lab members (including undergraduates) are welcome to attend but attendance is not required, except for thesis students, URF students, and students earning course credit.

In addition, we sometimes hold journal clubs in lieu of lab meeting presentations. Journal clubs will focus on discussing new and/or important research articles. Some weeks, we'll discuss a single article that everyone has read; other weeks, we'll each read a paper on a specific theme and do mini-presentations on each paper. As with our internal lab meetings, all full-time lab members are expected to attend these additional meetings, and part-time lab members are invited but not required to attend.

During extended periods of working remotely, such as during the COVID-19 pandemic, we will also have regular lab “check-ins” (currently on a Tuesday-Thursday schedule) to set up our goals for the week, encourage casual interactions, etc.

### Scheduling

In general for quick chats feel free to come knock on my door so we can discuss experiments, troubleshooting, ordering, etc. For all **scheduling** of meetings, individual leave, or other events that require advanced notice or planning, please send me a **calendar invite** to make sure that we both know the timing and expectations for these events. This includes for collaboration meetings, time off, general exams, committee meetings, etc. 

### Individual Meetings

At the beginning of each semester, I will set a schedule to meet with each full-time lab member for one hour a week. If we do not have anything to discuss in a given week, that's fine- we can just say hi or cancel it. Before each meeting, update your meeting agenda; this will also be a place where we document next steps. Over the summer, we may set the schedule on a weekly basis since summer schedules are more flexible and variable.

### Joint Lab Meetings

Occasionally we will participate in joint lab meetings, or join other labs for their lab meeting. As with our own meetings, be respectful, be supportive, and *be on time* at these meetings. The GS department is full of great colleagues and these meetings are an important opportunity for collaborative thinking and projects.

## Work Hours

One of the benefits of a career in academic research is that it is typically more flexible than other kinds of jobs. However, you should still treat it like a job. If you are employed for 40 hours a week, you should be working 40 hours a week. This applies to lab staff members and postdocs. You are not required to work over-time. For graduate students, I recognize that you have other demands on your time like classes and TA-ing but I still expect that you will be regularly engaged in your research.

Lab staff members are expected to keep regular hours (e.g., somewhere in the ballpark of 9-5). Graduate students and postdocs have more flexibility. However, in order to encourage lab interaction, I expect that all lab members will be in the lab (or available on Slack, when working remotely), at minimum, most weekdays between 11am and 4pm or so. If you’re going to be taking off from work on a normal workday (i.e., taking vacation or a personal or sick day), please let Devin know.

## Deadlines

If you need something from me by a particular deadline, please inform me as soon as you are aware of the deadline so that I can allocate my time as efficiently as possible. I will expect at least one week's notice, but I greatly prefer two weeks' notice. I will require two weeks' notice for letters of reference. If you do not adhere to these guidelines, I may not be able to meet your deadline. Please note that this applies to reading/ commenting on abstracts, papers, and manuscripts, in addition to filling out paperwork, etc. Reminder messages are appreciated as well!

## Presentations

I encourage you to seek out opportunities to present your research to the department, research community, or general public. If you are going to give a presentation (including posters and talks), be prepared to give a practice presentation to the lab at least one week ahead of time. Not only will this help you feel comfortable with the presentation, it will give you time to implement any feedback. I care about practice presentations because **a)** presenting your work is a huge part of being successful in science and it is important that you practice those skills as often as possible, and **b)** you are going to be representing not only yourself but also the rest of the lab.

There is a lab template for posters that you are free to modify as you see fit, but the header and general aesthetic should stay similar. If you have ideas for how to improve the poster template, please show the lab so we can decide whether to implement them as a group. This will help increase the visibility of our lab at conferences. There is no template for talks, and I encourage you to use your own style of presentation as long as it is polished and clear.

When making figures, it is helpful if you follow a few color-coding conventions, so that it’s easier to keep things consistent when I present your work in talks. For example, there is a common coloring scheme for multiplexed proteomics available in the shared Illustrator document. There are also common figures and illustrations available. If you have modifications or a new illustration, add a new artboard and show off your work!

## Lab Travel

In general, the lab will provide up to ***$2,000 per person per year*** for full-time lab members to present their work at major conferences (e.g., ASMS, Keystone, HuPO). This will be contingent on lab members submitting an abstract for a poster or oral presentation. In general, the work should be "new" and it should be appropriate for the conference. This will usually result in one conference per year. If travel expenses are being paid off of a grant, additional restrictions may apply (come speak with me if you are unsure).

If you are interested in attending a conference, come talk to me **at least 1 month** before the abstracts are due so that we can plan appropriately. The lab will pay for new lab members to attend one conference in their first year in lab (i.e. without presenting). If you wish to attend any other conference outside of these guidelines, come speak with me to ensure the availability of funds and appropriateness of the conference. **All of these guidelines, of course, depend on the availability of funds**. I highly recommend that lab members apply for other sources of funding available to them (e.g. departmental funds for grad students, ASMS travel awards).

## Letters of Reference/Recommendation

Letters of reference/recommendation are one of the many benefits of working in a research lab. I will write a letter for any student or lab member who has spent at least one year in the lab. Letters will be provided for shorter-term lab members in exceptional circumstances (e.g. new graduate students or postdocs applying for fellowships). I maintain this policy because I do not think that I can adequately evaluate someone who has been around for less than a year.
To request a letter of recommendation, please adhere to the deadline requirements described above. Send me your current CV and any relevant instructions for the contents of the letter. If you are applying for a grant, send me your specific aims or a short summary of the grant. In some but not all cases, I may ask you to draft a letter, which I will then revise to be consistent with my evaluation. This will ensure that I do not miss any details about your work that you think are relevant to the position you're applying for, and it will also help me complete the letter in a timely fashion. You are advised to send me a reminder message close to the letter deadline.

## Funding

Funding for the lab comes from a variety of sources, including the lab startup fund, federal agencies (e.g. NIH), private foundations, and internal funds from the University of Washington. I will oversee all aspects of the financial management of our funding sources. However, it is important to me to be transparent about where research money comes from and how it's spent. Please ask if you want to know more details. In general, external funds tend to be restricted to expenses related to a particular project or set of projects, whereas some of the internal funds are flexible in that they can be used for any justifiable work-related purpose. 

All research funded by external grants must acknowledge the funding agency and grant number upon publication. This is essential for documenting that we are turning their money into research findings. We must also submit a yearly progress report describing what we have accomplished. Lab members involved in the research will be asked to contribute to the progress report!

## Safety

Part of maintaining a great working environment in the lab is maintaining safe working habits. For more information on safety in the lab check out these resources:

* Laboratory Safety Manual: https://www.ehs.washington.edu/system/files/resources/uw-biosafety-manual.pdf
* EHS Trainings: https://www.ehs.washington.edu/training
* Biosafety Manual: https://www.ehs.washington.edu/system/files/resources/uw-biosafety-manual.pdf
* Exposure Response: https://www.ehs.washington.edu/system/files/resources/exposure-response-poster.pdf


### Personal Protective Equipment (PPE)

In accordance with UW and EHS standards expressed in the [Laboratory Safety Manual (LSM)](https://www.ehs.washington.edu/system/files/resources/uw-biosafety-manual.pdf) and the Biosafety Manual lab members will be required to adhere to EHS guidelines regarding personal attire.


***The current guidelines from EHS in the LSM are:***

#### Appropriate Clothing
The clothes you wear in the laboratory are an important consideration for personal safety and can
influence the severity of consequences of spills, splashes and burns. These guidelines should be
followed when working in the laboratory:

1. Shoes should fully cover the feet to protect against spills; no open-toed
shoes or sandals are permitted, and shoes constructed of mesh (such as
athletic shoes) are not recommended.
2. Clothing should fully cover your legs.
3. Materials you wear in the laboratory can make a difference. Many synthetic
fabrics may be dissolved by solvents or may melt into your skin, causing
more extensive burns if they catch on fire. Preferred materials are cotton,
wool, and resistant polyester. Synthetic materials, such as acrylics, rayon, and
polyester are not recommended.
4. Loose, flowing garments and scarves should be avoided; they may easily pick
up spills or trail through a burner flame.

#### Jewelry
Loose jewelry such as bracelets, watches and necklaces should be avoided since they may catch on
equipment. Avoid rings that can damage protective gloves or make removing gloves difficult.

#### Hair
Tie back long hair so it does not get caught in equipment, come in contact with chemicals or
interfere with your field of view.

### Project Specific PPE

Each project may require specific or specialized PPE. Before beginning new work, check the lab's SOPs, LSM, BUA, etc. to ensure that you are using the right PPE for your work. Feel free to contact Devin if you need further clarification or guidance.


