--- 
title: "Schweppe Lab Handbook"
author: "Devin Schweppe"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/LabHandbook
description: "This is a lab handbook for the Schweppe Lab within the Department of Genome Sciences at the University of Washington."
---

# Welcome!

Welcome to the Schweppe Lab Handbook. The handbook was developed by [Devin Schweppe](https://www.schweppelab.org/) as a guide for new and current members of the lab. The goal of this handbook is to provide resources, guidelines, and information to foster an environment of scientific excellence and personal development that is inclusive and (hopefully) fun. More information on the lab and department can be found through the following resources:

* [The Lab website](https://www.schweppelab.org)
* [The Lab Slack Channel](https://schweppelab.slack.com/)
* [Departmental website](https://www.gs.washington.edu/)

This handbook has been adapted from and influenced by several other works from the [ Morey](https://ccmorey.github.io/labHandbook/index.html), [ Peele](https://github.com/jpeelle/peellelab_manual/blob/master/peellelab_manual.pdf), and [Ritchey](http://www.thememolab.org/resources/) groups. The Schweppe Lab manual is licensed under the [Creative Commons Attribution 4.0 International License](https://creativecommons.org/licenses/by/4.0/).

<!--chapter:end:index.Rmd-->

# Introduction {#intro}

## Lab Member Expectations and Responsibilities

>I would especially emphasize the extent of my gratitude and thanks to my eager and able colleagues without whose efforts I would not be here today.
>-John B. Fenn

No one can accomplish the work we are striving to do alone. By joining this lab, you are jumping into a big, partially-completed project, whether you realize it or not.

### For Everyone

The following applies to all full-time, part-time, and undergraduate lab members.

***The Big Picture***

*	Do work that you are proud of. Do work that others will care about. If you feel as though your work does not meet these standards, let’s find a solution.
*	Double-check your work. Being a little obsessive is essential to good science.
*	Be supportive of your labmates. We are an inclusive team, act like it.
*	Work independently when you can, ask for help when you need it.
*	Share your knowledge. Exchanging knowledge and skills with your peers is the core of academic research.
*	Respect each others' strengths, weaknesses, differences, and beliefs.
*	Academia may feel different from other types of jobs, but it is still a job. You should treat coming into lab with the same respect that you would treat any other position. 
*	Communicate openly and respectfully with other members of the lab.

***The Small Picture***

*	Do not come into the lab if you are sick. Stay home and get healthy, and don't risk getting others sick.
*	Notify the lab manager or me if you will be taking the day off from work, either due to illness or vacation. If you are sick and you had experiments or meetings scheduled that day, notify your participants or collaborators and reschedule. Please also update your Slack status.
* *No food* is allowed at desks in the bays. Food can be consumed in the dry lab area, the common areas outside of the lab, or outside on a nice day!
*	Keep the lab tidy. Common areas should be kept free of clutter. Items left unattended may be cleaned, reclaimed, or recycled. If you're using lab equipment, put it away when you're done.
*	You are not expected to work on staff holidays. If you are being paid, then you are expected to work during university breaks (except for staff holidays or if you're taking your paid vacation/personal time).
*	Lock the doors to the lab if no one else is around, even if you're stepping out for a minute.
*	The dress code in academia is generally casual. My only request is that you look semi-professional when when presenting your work or interviewing candidates. Jeans are fine, gym clothes and pajamas are not.
*	When working remotely, you should be generally available over Slack and email during workdays (not necessarily responding immediately, but ideally within a few hours), and you should attend any scheduled remote lab meetings.

### For the PI
All of the points in the *Everyone* section, and you can expect me to:

*	Maintain a vision of where the lab is going.
*	Apply for and secure the funding necessary to keep the lab going.
*	Meet with you regularly to discuss your research projects. The definition of "regularly" may change over time or over the course of a project, but for now, I mean once a week or more often as needed.
*	Work with you to develop a mentoring and research plan tailored to your interests, needs, and career goals. We will meet in September each year to sketch out a strategic plan for the academic year that will keep you on track with your goals, and we will meet in June to review progress toward these goals.
*	Give you my perspective on academia and issues related to professional development.
*	Support your career development by introducing you to other researchers in the field, writing recommendation letters for you, providing you with opportunities to attend conferences when possible, and promoting your work in talks.
*	Care about you as a person and not just a scientist. I am happy to discuss with you any concerns or life circumstances that may be influencing your work, but it is entirely up to you whether and what you want to share. 
*	If you need extra support related to time management and productivity, I will brainstorm solutions with you and share what has worked for me and for others. 

### For Post-docs
All of the points in the *Everyone* section, and they are expected to:

*	Develop your own independent line of research.
*	Mentor undergraduate and graduate students on their research projects, when asked or when appropriate.
*	Apply for external funding (e.g., NRSA, K99, Damon-Runyon, Ford). I will hire postdocs only when there is funding available for at least a year; however, applying for external funding is a valuable experience and, if awarded, it will release those dedicated funds for other purposes.
*	Apply for jobs (academic or industry or otherwise) as soon as you are "ready" and/or by the beginning of your fourth year as a postdoc.
*	If you are planning to pursue a non-academic career, treat your postdoctoral research as seriously as you might if you were pursuing an academic career. We can discuss ways of making sure that you are getting the training you need, while still doing excellent research.
*	Remind me (the PI) that different scientific opinions can co-exist in the same lab!

### For Graduate Students
All of the points in the *Everyone* section, and they are expected to:

*	Develop a line of dissertation research. Ideally, your dissertation research will consist of at least 3 experiments that can be packaged into one thesis document.
*	Apply for external funding (e.g., NSF GRFP or NRSA). This is a valuable learning experience and a great honor if awarded.
*	Research what type of career you want to pursue, e.g., academic jobs that are research-focused or teaching-focused, non-academic jobs like data science or science writing. We can brainstorm ways of making sure you are getting the training that you need.
*	Stay up-to-date (and keep me up-to-date) on any deadlines that you need to meet to fulfill departmental requirements. In general, this includes your external funding applications, your qualifying exam, and your dissertation proposal and defense.
*	Prioritize time for research. It is easy to get caught up in coursework or TA-ing, but at the end of 5-ish years, you need to have completed a dissertation.

### For Lab Managers & Research Scientists
All of the points in the *Everyone* section, and they are expected to:

*	Maintain the lab IRB protocols and paperwork (e.g., archiving consent forms).
*	Oversee the hiring, scheduling, and training of undergraduate research assistants.
*	Maintain the lab internal website.
*	Keep the lab manager manual up to date.
*	Assist with participant recruitment and scheduling.
*	Assist other lab members with data collection or analysis (typically you will be assigned to particular projects).
*	Coordinate and take notes during weekly lab meetings.
*	Help to maintain an atmosphere of professionalism within the lab.
*	Work on your own research project.


## Lab Architecture
The PI, for better or worse, shoulders responsibility for the work conducted by her lab group. While everyone involved in the work will be acknowledged when work we have done is published or praised, the PI will always be primarily responsible for correcting problems when they arise, no matter who really caused them. Our work can be questioned years after it has been carried out and published, meaning the PI is the only person committed to this for long enough to realistically keep this commitment. 

For some post-doctoral and PGR projects, the researchers involved might share a long-term commitment to the research and be the "local PI" on the work. In those cases, they will act as the primary person responsible for those projects. Even so, the PI must always have access to enough information about these projects to independently reproduce analyses and replicate findings.

While the PI thinks in terms of large, multi-experiment projects, lab researchers at all levels will have the responsibility for individual experiments, projects, or component projects. Elements of any project must always be documented. Every project has designated milestones at which documentation should be completed, backed-up, and shared (at least with the lab group, often publicly).
  
Whenever a lab member moves on from the lab, every project they led must be documented and made accessible to the PI. At that point, if the project is not published, the PI must be given full editing authority along with the former lab member.

## Current Lab Members

Devin K Schweppe, PhD, Principal Investigator (PI)

### Postdoctoral Fellows

### Graduate Students

### Research Scientists


## Departmental Resources
The Department of Genome Sciences has many resources to aid your research and career, including:

* General Information: https://www.gs.washington.edu/ 
* DEI Initiatives: https://www.gs.washington.edu/about/dei/index.htm
* GS-IT: https://www.gs.washington.edu/computing/contact/index.htm
* GS Seminars: https://www.gs.washington.edu/news/seminar.htm
* Research Reports: https://www.gs.washington.edu/news/reports.htm
* Journal Club: https://www.gs.washington.edu/news/journal.htm



<!--chapter:end:01-intro.Rmd-->

# Code of Conduct {#code}

## General

In addition to the general expectations laid out above, I am dedicated to making our lab a safe, inclusive, and welcoming environment for all. Below you can find a specific code of conduct for behavior in the lab, as well as a broader discussion of what constitutes an inclusive environment. For more information on professional conduct see the [UW SoM Policy on Professional Conduct](https://www.gs.washington.edu/office/facultyresources/policies/conduct.pdf).

I encourage you also to visit the departmental site dedicated to [diversity, equity, and inclusion (DEI)](https://www.gs.washington.edu/about/dei/index.htm) as well as the UW HR site for DEI information: https://hr.uw.edu/diversity/

## Building an Inclusive Lab Environment

All members of the lab, along with visitors, are expected to agree to the following code of conduct. More information on UW anti-harassment resources are available through the [GS website](https://www.gs.washington.edu/academics/gradprogram/handbook/general/antiharassment.htm).

### Code of Conduct

The lab is dedicated to providing a harassment-free experience for everyone, regardless of gender, gender identity and expression, age, sexual orientation, disability, socioeconomic status, physical appearance, body size, race, national origin, or religion (or lack thereof). We do not tolerate harassment of lab members in any form.

All lab members will treat one another with respect and be sensitive to how one’s words and actions impact others. We do not tolerate the perpetuation of stereotypes; we do not tolerate other acts of microaggression ([more information](https://www.washington.edu/teaching/topics/inclusive-teaching/addressing-microaggressions-in-the-classroom/) via the UW CTL). We are a team. We stand up for one another. We learn from each other. We hold each other accountable.

## Scientific Integrity

### Reproducible Research

I expect that all of our research will be, at minimum, reproducible (when possible, we will also test for replicability). There are two main things you can do to improve the reproducibility of your research: 1) extensive note-taking (i.e., as much as you can manage) and 2) programming workflows with version control.

Programming workflows help with reproducibility because they take some of the human element out, and in an ideal scenario, you are left with a script or series of scripts that takes data from raw form to final product. Programming alone is not enough, though, because people can easily forget which script changes they made and when. Therefore, all projects that involve programming of any kind (so basically, all projects) must use some form of version control. I strongly recommend git in combination with GitHub (see below), unless you have a pre-existing workflow.

### Authorship

Authorship will be discussed prior to the beginning of a new project, so that expectations are clearly defined. However, changes to authorship may occur over the course of a project if a new person becomes involved or if someone is not fulfilling their planned role. In general, graduate students and postdocs will be a first author on publications on which they are the primary lead, and I will be a last/corresponding author.

### Old Projects

For projects that required significant lab resources (e.g. large scale proteomics experiments): Project "ownership" expires 2 years after data collection has ended or whenever the original primary lead relinquishes their rights to the study, whichever comes first. At that point, I reserve the right to re-assign the project (or not) as needed to expedite publication. This policy is intended to avoid situations in which a dataset languishes for a long period of time, while still giving publication priority to the original primary lead.

<!--chapter:end:02-code.Rmd-->

# General Policies {#general}

## PI Availability
I will be working on campus and available for meetings most days of the week. If my door is open, feel free to come say "hi". Barring an emergency, if my door is closed, send me a message or try me later rather than knock. I’m also happy to set ad-hoc meetings to discuss anything beyond weekly lab and individual meetings.

When working remotely, I’ll be similarly available over Slack and for ad-hoc meetings during regular office hours.


## Meetings

### Lab Meetings & Journal Club
Weekly lab meetings will be focused on project presentations and going over new data/methods. Lab meetings will last 1.5 hours. If at the end of 1.5 hours, we need more time to discuss something, we will schedule another meeting. Lab meeting plans and notes will be maintained in the #lab_-_meetings channel on Slack. **All full-time lab members** are expected to attend the weekly lab meeting. All part-time lab members (including undergraduates) are welcome to attend but attendance is not required, except for thesis students, URF students, and students earning course credit.

In addition, we sometimes hold journal clubs in lieu of lab meeting presentations. Journal clubs will focus on discussing new and/or important research articles. Some weeks, we'll discuss a single article that everyone has read; other weeks, we'll each read a paper on a specific theme and do mini-presentations on each paper. As with our internal lab meetings, all full-time lab members are expected to attend these additional meetings, and part-time lab members are invited but not required to attend.

During extended periods of working remotely, such as during the COVID-19 pandemic, we will also have regular lab “check-ins” (currently on a Tuesday-Thursday schedule) to set up our goals for the week, encourage casual interactions, etc.

### Individual Meetings

At the beginning of each semester, I will set a schedule to meet with each full-time lab member for one hour a week. If we do not have anything to discuss in a given week, that's fine- we can just say hi or cancel it. Before each meeting, update your meeting agenda; this will also be a place where we document next steps. Over the summer, we may set the schedule on a weekly basis since summer schedules are more flexible and variable.

### Joint Lab Meetings

Occasionally we will participate in joint lab meetings, or join other labs for their lab meeting. As with our own meetings, be respectful, be supportive, and *be on time* at these meetings. The GS department is full of great colleagues and these meetings are an important opportunity for collaborative thinking and projects.

## Work Hours

One of the benefits of a career in academic research is that it is typically more flexible than other kinds of jobs. However, you should still treat it like a job. If you are employed for 40 hours a week, you should be working 40 hours a week. This applies to lab staff members and postdocs. You are not required to work over-time. For graduate students, I recognize that you have other demands on your time like classes and TA-ing but I still expect that you will be regularly engaged in your research.

Lab staff members are expected to keep regular hours (e.g., somewhere in the ballpark of 9-5). Graduate students and postdocs have more flexibility. However, in order to encourage lab interaction, I expect that all lab members will be in the lab (or available on Slack, when working remotely), at minimum, most weekdays between 11am and 4pm or so. If you’re going to be taking off from work on a normal workday (i.e., taking vacation or a personal or sick day), please let Devin know.

## Deadlines

If you need something from me by a particular deadline, please inform me as soon as you are aware of the deadline so that I can allocate my time as efficiently as possible. I will expect at least one week's notice, but I greatly prefer two weeks' notice. I will require two weeks' notice for letters of reference. If you do not adhere to these guidelines, I may not be able to meet your deadline. Please note that this applies to reading/ commenting on abstracts, papers, and manuscripts, in addition to filling out paperwork, etc. Reminder messages are appreciated as well!

## Presentations

I encourage you to seek out opportunities to present your research to the department, research community, or general public. If you are going to give a presentation (including posters and talks), be prepared to give a practice presentation to the lab at least one week ahead of time. Not only will this help you feel comfortable with the presentation, it will give you time to implement any feedback. I care about practice presentations because **a)** presenting your work is a huge part of being successful in science and it is important that you practice those skills as often as possible, and **b)** you are going to be representing not only yourself but also the rest of the lab.

There is a lab template for posters that you are free to modify as you see fit, but the header and general aesthetic should stay similar. If you have ideas for how to improve the poster template, please show the lab so we can decide whether to implement them as a group. This will help increase the visibility of our lab at conferences. There is no template for talks, and I encourage you to use your own style of presentation as long as it is polished and clear.

When making figures, it is helpful if you follow a few color-coding conventions, so that it’s easier to keep things consistent when I present your work in talks. For example, there is a common coloring scheme for multiplexed proteomics available in the shared Illustrator document. There are also common figures and illustrations available. If you have modifications or a new illustration, add a new artboard and show off your work!

## Lab Travel

The lab will typically pay for full-time lab members to present their work at major conferences (e.g. ASMS, Keystone, HuPO). In general, the work should be "new" in that it has not been presented previously, and it should be appropriate for the conference. This will usually result in one conference per year. Meal costs will be reimbursed for people who are presenting work from the lab. The lab will also pay for new grad students and postdocs to attend one conference in their first year in lab (i.e. without presenting). If you wish to attend any other conference outside of these guidelines, come speak with me. If travel expenses are being paid off of a grant, additional restrictions may apply (come speak with me). All of these guidelines, of course, depend on the availability of funds. I recommend that lab members apply for other sources of funding available to them (e.g. departmental funds for grad students, ASMS travel awards).

## Letters of Reference/Recommendation

Letters of reference/recommendation are one of the many benefits of working in a research lab. I will write a letter for any student or lab member who has spent at least one year in the lab. Letters will be provided for shorter-term lab members in exceptional circumstances (e.g. new graduate students or postdocs applying for fellowships). I maintain this policy because I do not think that I can adequately evaluate someone who has been around for less than a year.
To request a letter of recommendation, please adhere to the deadline requirements described above. Send me your current CV and any relevant instructions for the contents of the letter. If you are applying for a grant, send me your specific aims or a short summary of the grant. In some but not all cases, I may ask you to draft a letter, which I will then revise to be consistent with my evaluation. This will ensure that I do not miss any details about your work that you think are relevant to the position you're applying for, and it will also help me complete the letter in a timely fashion. You are advised to send me a reminder message close to the letter deadline.

## Funding

Funding for the lab comes from a variety of sources, including the lab startup fund, federal agencies (e.g. NIH), private foundations, and internal funds from the University of Washington. I will oversee all aspects of the financial management of our funding sources. However, it is important to me to be transparent about where research money comes from and how it's spent. Please ask if you want to know more details. In general, external funds tend to be restricted to expenses related to a particular project or set of projects, whereas some of the internal funds are flexible in that they can be used for any justifiable work-related purpose. 

All research funded by external grants must acknowledge the funding agency and grant number upon publication. This is essential for documenting that we are turning their money into research findings. We must also submit a yearly progress report describing what we have accomplished. Lab members involved in the research will be asked to contribute to the progress report!

## Safety

Part of maintaining a great working environment in the lab is maintaining safe working habits. For more information on safety in the lab check out these resources:

* EHS Trainings: https://www.ehs.washington.edu/training
* Biosafety Manual: https://www.ehs.washington.edu/system/files/resources/uw-biosafety-manual.pdf
* Exposure Response: https://www.ehs.washington.edu/system/files/resources/exposure-response-poster.pdf

<!--chapter:end:03-general.Rmd-->

# Data and Instrumentation {#data}

## Instrumentation

We work with highly sensitive, but also very expensive instrumentation. Below find guidelines for the use of instrumentation in the lab.

Instrumentation and equipment need to be maintained so that every member of the lab has access to complete their research projects. When you have finished using an instrument, you should leave it in a condition so that the next person who needs to use it does not need to fix/clean it. This essential to keeping the lab functioning efficiently.

### Mass spectrometers

By far the best part of our armamentarium to understand whole proteome dynamics, the mass spectrometers (MSs) are fantastic resources within the lab. Over the course of your work in the lab there will be opportunities to learn more about using, running and fixing the the MSs. I highly encourage you to learn as much as you can as well through the literature to understand what the instruments are capable of and not capable of.

If you run into issues in the operation of the instruments (including but not limited to hardware malfunctions or failures and software faults or errors), **alert me immediately**! These problems cannot be ignored and are more likely than not to cause considerable harm to the instrument if left unattended. Unaddressed issues are also likely to result in expensive instrument repairs (tens of thousands of dollars).

If you notice significant degradation of instrument performance during or after your runs, alert both Devin and the next user so that samples are not lost!

### HPLCs

Separation or enrichment of peptides, proteins, and small molecules using high performance liquid chromatography (HPLC) is an integral part of our workflows. Normal HPLCs are often quite robust, while nano-HPLCs can be prone to failure due to their high operational pressures. As with the mass spectrometers any issues with the hardware or software need to be addressed immediately.

## Data, Data, Data

### Scripts and Code

All scripts and code used for lab projects (including programs, websites, tools, data analysis work) should be deposited or version controlled in lab storage/servers. This includes depositing repositories in the lab GitHub. 

### Raw Data

Raw data will be backed up in at least two places to ensure that should it need to be accessed it can be. This is especially important for published data as someone may ask for these files years later. Unpublished data should be similarly managed to ensure that we do not need to revisit the same basic work again. If you are unsure or where to store your data contact Devin!

### Data sharing

Data for publication will be shared through PRIDE/ProteomeXchange or a similar repository. Sharing these data with the general community is essential for future development of MS methods.

### Lab Storage

Data can be stored in the following places:

* **Lab server**
  + *Store*: Raw data, search results, basic analyses.
* **Lab partition of departmental storage**
  + *Store*: Raw data, data analysis, programs, general utilities, presentations, lab meeting information, protocols, collaboration data.
* **Lab GitHub**
  + *Store*: All code/scripts. Yup, all of it.
* **Google Drive (in shared folders)**
  + *Store*: Personal project information, presentations, figures, pre-print manuscripts, proofs, collaboration data.



<!--chapter:end:04-data.Rmd-->

# Literature {#literature}

Background literature for the lab can be found in the "Getting Started" Google Drive folder. You will be given access to this upon joining. If you need access, ask Devin about this.

Below find links to papers that may be of interest to explore new topics or get caught up on where the lab is now.

## Proteomics

## Multiplex quantitation

## Proteome data analysis

## Adaptive instrument control

<!--chapter:end:05-literature.Rmd-->

